
import { GoogleGenAI } from "@google/genai";
import { MemeStyle } from "../types";
import { GOAT_LOGO_URL } from "../constants";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || "" });

async function imageUrlToBase64(url: string): Promise<string> {
  const response = await fetch(url);
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = (reader.result as string).split(',')[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

export async function generateGoatMeme(prompt: string, style: MemeStyle): Promise<string> {
  const logoBase64 = await imageUrlToBase64(GOAT_LOGO_URL);
  
  let styleInstruction = "";
  if (style === 'realistic') styleInstruction = "Ensure the image is photorealistic and cinematic.";
  if (style === 'cartoon') styleInstruction = "Ensure the image is in a vibrant, high-quality 2D cartoon animation style.";
  if (style === 'gta') styleInstruction = "Ensure the image is in the iconic Grand Theft Auto V loading screen art style with thick outlines and cell shading.";

  const finalPrompt = `Using the attached image as a character reference for the goat, generate a new image based on this scenario: ${prompt}. ${styleInstruction} If the user mentions 'goat', use the exact goat character from the reference image.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: logoBase64,
            mimeType: 'image/png'
          }
        },
        {
          text: finalPrompt
        }
      ]
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1"
      }
    }
  });

  let imageUrl = "";
  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      imageUrl = `data:image/png;base64,${part.inlineData.data}`;
      break;
    }
  }

  if (!imageUrl) throw new Error("No image generated by AI");
  return imageUrl;
}

export const RANDOM_PROMPTS = [
  "goat riding a rocket to the moon",
  "goat sitting on a golden throne wearing sunglasses",
  "goat playing poker with high stakes",
  "goat djing at a massive music festival",
  "goat as a solana developer coding on a laptop",
  "goat walking down a red carpet as a celebrity",
  "goat doing a slam dunk on a basketball court",
  "goat surfing on a giant wave of gold coins"
];
